pipeline {
  agent none
  stages {
    stage('Build and compile java program') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn clean install'
	sh 'compile'
      }
    }
    stage('Front-end') {
       agent {
        docker { image 'node:16-alpine' }
      }
       steps {
        sh 'node --version'
      }
    }
  }
}
