
pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'apache/beam_java17_sdk' }
      }
      steps {
        sh 'java --version'
        sh 'javac my-first-pipeline/HelloJenkins.java'
        sh 'java my-first-pipeline/HelloJenkins'
       
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
