
pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'ranniuser/hellojenkins:v1' }
      }
      steps {
        sh 'java --version'
        sh 'javac HelloJenkins.java'
        sh 'java HelloJenkins'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
